spring:
  application:
    name: battle-service
  profiles:
    active: "dev"

---

spring:
  profiles: dev
server:
  port : 8082

---

spring:
  profiles: prod
server:
  port : 8080