spring:
  application:
    name: statistic-service
  profiles:
    active: "dev"

---

spring:
  profiles: dev
server:
  port : 8083

---

spring:
  profiles: prod
server:
  port : 8080